apiVersion: v1
kind: ConfigMap
metadata:
  name: shopcloud-config
  namespace: default
data:
  APP_NAME: "ShopCloud"
  APP_ENV: "production"
  APP_VERSION: "1.0.0"
  FRONTEND_URL: "http://frontend-service:80"
  USER_SERVICE_URL: "http://user-service:80"
  PRODUCT_SERVICE_URL: "http://product-service:80"
  ORDER_SERVICE_URL: "http://order-service:80"
  NOTIFICATION_SERVICE_URL: "http://notification-service:80"